lab:
  Mono:
    black:
      max:
      - 89
      - 255
      - 255
      min:
      - 0
      - 0
      - 0
    blue:
      max:
      - 255
      - 255
      - 110
      min:
      - 0
      - 0
      - 0
    green:
      max:
      - 255
      - 110
      - 255
      min:
      - 47
      - 0
      - 135
    orange:
      max:
      - 255
      - 255
      - 255
      min:
      - 173
      - 52
      - 153
    red:
      max:
      - 255
      - 255
      - 255
      min:
      - 13
      - 155
      - 130
    white:
      max:
      - 255
      - 255
      - 255
      min:
      - 193
      - 0
      - 0
    yellow:
      max:
      - 255
      - 255
      - 255
      min:
      - 42
      - 123
      - 138
  Stereo:
    black:
      max:
      - 90
      - 255
      - 255
      min:
      - 0
      - 0
      - 0
    blue:
      max:
      - 228
      - 189
      - 114
      min:
      - 51
      - 66
      - 1
    green:
      max:
      - 255
      - 114
      - 255
      min:
      - 0
      - 0
      - 135
    orange:
      max:
      - 255
      - 223
      - 255
      min:
      - 86
      - 72
      - 144
    red:
      max:
      - 255
      - 255
      - 255
      min:
      - 13
      - 158
      - 83
    white:
      max:
      - 255
      - 255
      - 255
      min:
      - 193
      - 0
      - 0
    yellow:
      max:
      - 255
      - 255
      - 255
      min:
      - 48
      - 118
      - 137
size:
  height:
  - 480
  width:
  - 640
